### ISSUE TITLE
你这个缓存好像没起到作用啊……

### ISSUE THREAD

**Issue by mengkunsoft** [Tokinx/NeteaseCloudMusic-php#2]
代码里先调用了
`$play_list = $netease->playlist($_GET['id']);`
请求到了实时的结果，然后再判断
`if (file_exists($save)) {`
拿缓存……

这不是无论缓存存不存在都进行了网络请求么……

**Comment by Tokinx** [comment]
那你看一下缓存的json的修改时间

**Comment by Tokinx** [comment]
好吧，我明白你的意思了。不知道当时脑子怎么混沌了

**Comment by Tokinx** [comment]
周末我重构一下，现在的JS乱糟糟的。。。看看用原生JS写算了。。。

**Comment by mengkunsoft** [comment]
你这 JS 已经够整洁了。相比之下，我的 [MusicPlayer](https://github.com/mengkunsoft/MKOnlineMusicPlayer) 简直就是一坨 💩 （我自己都看不下去了→_→）
